### ISSUE TITLE
Need ability to List Recommendations

### ISSUE THREAD

**Issue by sh6900** [CSCI-GA-2820-SP23-001/recommendations#1]

**Comment by sh6900** [comment]
As a Marketing Manager
I need the ability to list all recommendations made to a given user  
so that I can track the product recommendations being offered
   
Assumptions:
- We will store recommendations in a PostgreSQL database
- Empty list of recommendations will be gracefully processed by the consuming layer. Error to list recommendations is a different scenario where this service is unable to query and fetch recommendations
   
 Acceptance Criteria:  

 Given this service is running
 When I list recommendations for a user
 Then I should see a list of all recommendations stored in the DB for this user

**Comment by christyekim** [comment]
Scrum Master’s Note from Backlog Refinement Meet:
----------------------------------------------------------------
Finalized label, estimate, and sprint assignment as discussed during meeting

**Comment by sh6900** [comment]
@olluyeancah , great job adding many tests!
The nosetests log you've shared indicates that line number 61 in routes.py has missing coverage. Could you please review and update the pull request so that we won't have to revisit this section later?
Rest everything looks great!

**Comment by olluyeancah** [comment]
@sh6900 missing coverage has been fixed. You can review now.
