### ISSUE TITLE
Need ability to see popular (AKA most viewed recent) products

### ISSUE THREAD

**Issue by christyekim** [CSCI-GA-2820-SP23-001/recommendations#10]
**As an** End Consumer
**I need** the ability to see the most popular products (AKA most viewed recent products)
**So that** I can identify and explore products to buy
   
 ### Details and Assumptions
* We will store and update recommendations in a PostgreSQL database
* Empty list of recommendations will be gracefully processed by the consuming layer
* Error to count product views is a different scenario where this service is unable to query and store recommendations
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given this service is running
 When I query popular products on "/recommendations/popular" route
 Then I should see popular products identified from the DB
```

**Comment by jrubnitz** [comment]
Product Owner’s Note:
----------------------------
Low priority feature parked for later sprints
