### ISSUE TITLE
Need ability to store Recommendations through DB with published schema

### ISSUE THREAD

**Issue by olluyeancah** [CSCI-GA-2820-SP23-001/recommendations#4]
**As a Backend Engineer**, 
**I need to be able to** store recommendations
**so that Users/customers** can interact seamlessly and effectively with our recommendation system.

_Details & Assumptions:_
- Our choice of database is PostgreSQL

_Acceptance Criteria:_
- Primary keys and foreign keys should be explicitly stated.
- Duplication of records should be avoided.
- The database model should be designed for scalability

------------------
Edit 1:  @sh6900 

### DB Schema:
----------------------------------------------------------------
id................................Integer...Primary Key, Unique Recommendation ID
product_id.................Integer...Foreign Key, from Products service (name, rating, price, etc. owned by them)
user_id.......................Integer...Foreign Key, from Customers service (all account details owned by them)
user_segment............String.....Segment (Class) Description (E.g.: Student\Pet Owner\New Parent\etc.)
viewed_in_last7d.......Boolean..Recently viewed or not
bought_in_last30d.....Boolean..Recently bought or not
last_relevance_date... Date.......To see how recent the recommendation is (Can be arrival\viewed\bought\etc.)
recommendation_type...Enum...SIMILAR_PRODUCT, RECOMMENDED_FOR_YOU, UPGRADE,
...................................................FREQ_BOUGHT_TOGETHER, ADD_ON, TRENDING, TOP_RATED,
...................................................NEW_ARRIVAL, or UNKNOWN

### Supported Methods:
---------------------
Recommendation.all()                        [List]
Recommendation.find()                      [By ID]
Recommendation.find_or_404()
Recommendation.find_by_product_id()
Recommendation.find_by_user_id()
Recommendation.find_by_user_segment()
Recommendation.find_by_viewed_in_last7d()
Recommendation.find_by_bought_in_last30d()
Recommendation.find_by_last_relevance_date()
Recommendation.find_after_last_relevance_date()
Recommendation.find_by_recommendation_type()

**Comment by sh6900** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/recommendations-spring23-001-63ec3b19cf73b0c219a97429/issues/CSCI-GA-2820-SP23-001/recommendations/4?planning-poker) with Zenhub @christyekim @olluyeancah @andersonnyc @jrubnitz

**Comment by christyekim** [comment]
Scrum Master’s Note from Backlog Refinement Meet:
----------------------------------------------------------------
Finalized label, estimate, and sprint assignment as discussed during meeting

**Comment by olluyeancah** [comment]
Add details on keys

**Comment by sh6900** [comment]
Updated the description to include DB schema and list of supported methods

**Comment by sh6900** [comment]
Test Report:

Test Flask CLI Commands
- It should call the db-create command

 Test Cases for Recommendation Model 
- It should Create a Recommendation and add it to the database
- It should Create a Recommendation and assert that it exists
- It should Delete a Recommendation
- It should deserialize a Recommendation
- It should not deserialize a bad bought_in_last30d attribute
- It should not deserialize bad data
- It should not deserialize a bad recommendation_type attribute
- It should not deserialize a bad viewed_in_last7d attribute
- It should not deserialize a Recommendation with missing data
- It should Find Recommendations after last_relevance_date
- It should Find Recommendations by bought_in_last30d
- It should Find Recommendations by last_relevance_date
- It should Find Recommendations by Product ID
- It should Find Recommendations by recommendation_type
- It should Find Recommendations by User ID
- It should Find a Recommendation by User Segment
- It should Find Recommendations by viewed_in_last7d
- It should Find a Recommendation by ID
- It should Find a Recommendation by ID or return 404_NOT_FOUND if not found
- It should return 404_NOT_FOUND for ID not found
- It should List all Recommendations in the database
- It should Read a Recommendation
- It should serialize a Recommendation
- It should Update a Recommendation
- It should Not Update a Recommendation with no ID

Recommendation Server Tests
- It should be healthy
- It should call the Home Page

Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
service/__init__.py                   18      3    83%   31-34
service/common/cli_commands.py         7      0   100%
service/common/error_handlers.py      38     19    50%   32, 38-40, 51-53, 62-64, 77-79, 92-94, 107-109
service/common/log_handlers.py        11      1    91%   35
service/common/status.py              45      0   100%
service/config.py                      5      0   100%
service/models.py                    119      0   100%
service/routes.py                     14      1    93%   54
----------------------------------------------------------------
TOTAL                                257     24    91%
----------------------------------------------------------------------
Ran 28 tests in 0.694s

OK



App Summary on Browser:

{
  "name": "Recommendations REST API Service",
  "paths": "http://127.0.0.1:8000/recommendations",
  "version": "1.0"
}
